Excercise 8
stepansojka/react-training pull request #7
Opened 2019-03-13 07:23 UTC by stepansojka

2019-03-13 07:24 UTC, stepansojka commented
couldn't get crudReducer working because of a dependency problem with react-redux - will discuss in person

2019-03-13 14:33 UTC, branoholy requested changes

2019-03-13 14:33 UTC, branoholy commented on src/index.js
> +import * as routes from "router/routes";
It's common to use namespaces in pascal case and I would put it into `modules/` folder.
```suggestion
import * as Routes from "modules/router/routes";
```

2019-03-13 14:33 UTC, branoholy commented on src/index.js
> +const router = buildRouter([routes.USER_LIST, routes.USER_DETAIL], {
It's quite common to create an array with all routes somewhere. Probably in `routes.js`. But depends on you.

2019-03-13 14:33 UTC, branoholy commented on src/modules/crud/crud-saga.js
> +      return {};
This is actually not necessary but it's not mentioned in the docs so it's not your fault.

2019-03-13 14:33 UTC, branoholy commented on src/modules/users/components/user-detail.js
> +    regnalNumber: PropTypes.string.isRequired
`skills` are missing

2019-03-13 14:33 UTC, branoholy commented on src/modules/users/user-reducer.js
> +export const userReducer = createReducer({}, {});
It seems like it can be removed now. :slightly_smiling_face:

2019-03-13 14:33 UTC, branoholy commented on src/modules/users/users-saga.js
>    yield fork(fetchUsers);
This shouldn't be necessary because we don't want to fetch users when the app is started but only when the user list route is loaded.

2019-03-13 14:33 UTC, branoholy commented on src/modules/crud/crud-saga.js
> +      };
Missing fetch params for the detail route.

2019-03-13 14:33 UTC, branoholy commented on src/index.js
> +router.start();
I think it's better to start the router later when the store is ready. Not sure if it correctly propagates the first transition to the store now. Also, you can render the app when the router is ready if you use a callback (see the arrow function). I would rather do it in the following order:

```ts
const router = buildRouter(...);
const store = buildStore(...);

router.start(() => ReactDOM.render(
  <Provider store={store}>
    <Root />
  </Provider>,
  document.getElementById("root")
));

2019-03-13 14:33 UTC, branoholy commented on src/modules/root/root-reducer.js
>    user: userReducer,
Not necessary anymore.

2019-03-14 14:02 UTC, branoholy requested changes

2019-03-14 14:02 UTC, branoholy commented on src/modules/users/components/user-detail.js
> +        }),
Missing `.isRequired`.

2019-03-14 14:02 UTC, branoholy commented on src/modules/crud/crud-saga.js
> +          schema: users
I would expect an effect and schema for a single user. :slightly_smiling_face:

2019-03-14 14:12 UTC, merged

2019-03-14 15:10 UTC, stepansojka commented on src/modules/crud/crud-saga.js
> +          schema: users
Yea I used it with all users for debugging and then forgot - fixed now.